//These are all the products available to be picked

let modelsJson = [
    {id:1, name:'Radiator-engine cooling 60782A Nissens', img:'_imagens/carparts/Cooling system & heating/radiator1.jpg', price:[101.48]},
    {id:2, name:'Wing Mirror * HAGUS * 0910814', img:'_imagens/carparts/Cooling system & heating/wing1.jpg', price:[21.51]},
    {id:3, name:'Shock Absorber', img:'_imagens/carparts/Cooling system & heating/shock1.jpg', price:[23.14]},
    {id:4, name:'Radiator Hose 32599 FEBI', img:'_imagens/carparts/Cooling system & heating/radiator2.jpg', price:[191.58]},
    {id:5, name:'Flat Rear View Mirror with suction cup', img:'_imagens/carparts/Cooling system & heating/flat1.jpg', price:[7.95]},
    {id:6, name:'Top Strut Mount 22502 FEBI', img:'_imagens/carparts/Cooling system & heating/top1.jpg', price:[22.83]},
    {id:7, name:'Fan-radiator 14742 FEBI', img:'_imagens/carparts/Cooling system & heating/fan1.jpg', price:[191.58]},
    {id:8, name:'Ventilation Grille, bumper', img:'_imagens/carparts/Cooling system & heating/vent1.jpg', price:[28.36]},
    {id:9, name:'Coil Spring', img:'_imagens/carparts/Cooling system & heating/coil2.jpg', price:[14.54]},
    {id:10, name:'Thermostat, coolant 18286 FEBI', img:'_imagens/carparts/Cooling system & heating/termostatus1.jpg', price:[191.58]},
    {id:11, name:'Mount Bracket, bumper 4019567 Van Wezel', img:'_imagens/carparts/Cooling system & heating/mount1.jpg', price:[6.87]},
    {id:12, name:'Rubber Buffer, suspension 36848 FEBI', img:'_imagens/carparts/Cooling system & heating/rubber1.jpg', price:[6.01]},
    {id:13, name:'Cooler Module 4300M499', img:'_imagens/carparts/Cooling system & heating/cooler1.jpg', price:[191.58]},
    {id:14, name:'Ford emblem front grille', img:'_imagens/carparts/Cooling system & heating/ford1.jpg', price:[17.26]},
    {id:15, name:'Spring Cap', img:'_imagens/carparts/Cooling system & heating/spring1.jpg', price:[5.70]},
    {id:16, name:'Dryer-air conditioning', img:'_imagens/carparts/Cooling system & heating/dryer1.jpg', price:[31.27]},
    {id:17, name:'Wing 5829657 Van Wezel', img:'_imagens/carparts/Cooling system & heating/wing2.jpg', price:[48.57]},
    {id:18, name:'Rod/Strut-stabiliser ProKit 24122 Febi ProKit', img:'_imagens/carparts/Cooling system & heating/rod1.jpg', price:[12.36]},
    {id:19, name:'Coil, magnetic-clutch compressor', img:'_imagens/carparts/Cooling system & heating/coil1.jpg', price:[15.65]},
    {id:20, name:'Panelling, mudguard', img:'_imagens/carparts/Cooling system & heating/panel1.jpg', price:[8.72]},
    {id:21, name:'AutoStyle lowering springs Volkswagen Transporter T4 91- 50mm', img:'_imagens/carparts/Cooling system & heating/auto1.jpg', price:[80.95]},
    {id:22, name:'Injector Nozzle-expansion valve', img:'_imagens/carparts/Cooling system & heating/injector1.jpg', price:[1.54]},
    {id:23, name:'Mudflap kit universal 36x21cm', img:'_imagens/carparts/Cooling system & heating/mud1.jpg', price:[9.18]},
    {id:24, name:'AP Coilover Kit Ford Puma 3 / 1997- with fork Montage at the rear', img:'_imagens/carparts/Cooling system & heating/ap1.jpg', price:[489.00]},
    {id:25, name:'Heat Exchanger-interior heating', img:'_imagens/carparts/Cooling system & heating/heat1.jpg', price:[11.53]},
    {id:26, name:'Seal-rear windscreen', img:'_imagens/carparts/Cooling system & heating/seal1.jpg', price:[45.30]},
    {id:27, name:'Suspension Kit, coil springs / shock absorbers STRightT KIT', img:'_imagens/carparts/Cooling system & heating/kit1.jpg', price:[369.00]},
    {id:28, name:'Interior Blower 18780 FEBI', img:'_imagens/carparts/Cooling system & heating/interior1.jpg', price:[32.09]},
    {id:29, name:'Jack Support Plate', img:'_imagens/carparts/Cooling system & heating/jack1.jpg', price:[7.48]},
    {id:30, name:'Air Spring-suspension', img:'_imagens/carparts/Cooling system & heating/air1.jpg', price:[202.05]},
    {id:31, name:'Additional Water Pump', img:'_imagens/carparts/Cooling system & heating/water1.jpg', price:[111.38]},
    {id:32, name:'Gas Spring-boot-/cargo area', img:'_imagens/carparts/Cooling system & heating/gas1.jpg', price:[13.15]},
    {id:33, name:'Bush, leaf spring', img:'_imagens/carparts/Cooling system & heating/bush1.jpg', price:[4.46]},
    {id:34, name:'Coolant Longlife -36 1L mixable', img:'_imagens/carparts/Cooling system & heating/coolant1.jpg', price:[3.95]},
    {id:35, name:'Sidewall', img:'_imagens/carparts/Cooling system & heating/sidewall1.jpg', price:[91.81]},
    {id:36, name:'Set of universal spring blocks-6 pieces', img:'_imagens/carparts/Cooling system & heating/set1.jpg', price:[14.20]},
    {id:37, name:'Kroon-Oil 04302 Antifreeze Coolant -26 5L', img:'_imagens/carparts/Cooling system & heating/kroon1.jpg', price:[11.95]},
    {id:38, name:"Sticker 3D '' Italia Flag '' 3st.", img:'_imagens/carparts/Cooling system & heating/sticker1.jpg', price:[5.95]},
    {id:39, name:'Elevation springs set', img:'_imagens/carparts/Cooling system & heating/elev1.jpg', price:[245.95]},
    {id:40, name:'Sensor-coolant temperature 29318 FEBI', img:'_imagens/carparts/Cooling system & heating/sensor1.jpg', price:[7.74]},
    {id:41, name:'Foliatec Plastic Tint Spray - red 1x150ml', img:'_imagens/carparts/Cooling system & heating/spray1.jpg', price:[12.30]},
    {id:42, name:'Suspension Sphere-pneumatic suspension', img:'_imagens/carparts/Cooling system & heating/sphere1.jpg', price:[40.81]},
];